# Generated by Django 3.2.11 on 2022-01-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_ride_special_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='special_request',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
