# Generated by Django 3.2.11 on 2022-01-27 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Economy', 'Economy'), ('Intermediate', 'Intermediate'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20, null=True)),
                ('license_plate_number', models.CharField(max_length=200, null=True)),
                ('max_number_passengers', models.IntegerField(null=True)),
                ('special_request', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_or_not', models.BooleanField(default=False)),
                ('destination', models.CharField(max_length=60)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('vehicle_type', models.CharField(choices=[('Economy', 'Economy'), ('Intermediate', 'Intermediate'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Open', max_length=20, null=True)),
                ('is_reached', models.BooleanField(default=False)),
                ('total_passengers', models.IntegerField(null=True)),
                ('sharer_number', models.IntegerField(null=True)),
                ('special_request', models.CharField(blank=True, max_length=20, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
