# Generated by Django 3.2.11 on 2022-01-28 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_ride_total_sharers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='total_sharers',
        ),
        migrations.AddField(
            model_name='myuser',
            name='total_sharers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_people',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, to='account.myUser'),
        ),
    ]
