# Generated by Django 4.0.1 on 2022-01-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_driver',
        ),
    ]
