# Generated by Django 3.2.11 on 2022-01-26 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_remove_driver_is_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_or_not', models.BooleanField(default=False)),
                ('destination', models.CharField(max_length=60)),
                ('arrival_time', models.DateTimeField(help_text='Please using format: <em>MM-DD-YYYY HH:mm<em>')),
                ('vehicle_type', models.CharField(choices=[('Economy', 'Economy'), ('Intermediate', 'Intermediate'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Open', max_length=20, null=True)),
                ('is_reached', models.BooleanField(default=False)),
                ('total_passengers', models.IntegerField(null=True)),
                ('sharer_number', models.IntegerField(null=True)),
                ('special_request', models.CharField(blank=True, max_length=20, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.driver')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
